"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Leaf, LogOut } from "lucide-react";
import { browserSupabase } from "@/lib/browser";
export default function Login() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  return <main className="login-page"><div className="login-art"><a className="brand" href="/">fkcyn<span className="brand-dot" /></a><div className="login-sculpture"><Leaf size={100} strokeWidth={.8} /></div><p className="eyebrow">YOUR LITTLE CORNER OF THE WORLD</p><h1>พื้นที่ของเรา<br />เรื่องราวของทุกวัน<span>.</span></h1><p>เก็บวันฝนพรำ และมองท้องฟ้าของวันพรุ่งนี้</p></div><section className="login-panel card"><Link className="text-link" href="/"><ArrowLeft size={15} />กลับแดชบอร์ด</Link><p className="eyebrow">WELCOME HOME</p><h2>กลับมาที่พื้นที่ของคุณ</h2><p>เข้าสู่ระบบด้วยบัญชี Supabase ที่ตั้งไว้</p><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); try { const client = browserSupabase(); if (!client) throw new Error("ยังไม่ได้ตั้งค่า Supabase สามารถกลับไปดูโหมดตัวอย่างได้ค่ะ"); const { error } = await client.auth.signInWithPassword({ email, password }); if (error) throw new Error("อีเมลหรือรหัสผ่านไม่ถูกต้อง หรือบริการยังไม่พร้อม"); window.location.href = "/"; } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><label>อีเมล<input type="email" autoComplete="username" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>รหัสผ่าน<input type="password" autoComplete="current-password" required value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" /></label>{error && <div className="notice error-notice">{error}</div>}<button type="submit" className="primary-button" disabled={busy}>{busy ? "กำลังเข้าสู่ระบบ…" : "เข้าสู่ระบบ"}<ArrowRight size={17} /></button></form><button className="text-link logout-button" onClick={async () => { await browserSupabase()?.auth.signOut(); window.location.href = "/"; }}><LogOut size={14} />ออกจากบัญชีบนเครื่องนี้</button><p className="micro-note">สร้างบัญชีส่วนตัวใน Supabase Auth และระบุ UUID ใน DASHBOARD_USER_ID ก่อนใช้งานจริง</p></section></main>;
}
