import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { thaiDay } from "../lib/rain";
const env = Object.fromEntries(readFileSync(".env.local", "utf8").split(/\r?\n/).filter(s => s.includes("=") && !s.startsWith("#")).map(s => [s.slice(0, s.indexOf("=")), s.slice(s.indexOf("=") + 1)]));
const base = process.env.TEST_BASE_URL ?? "http://127.0.0.1:3000";
// This test writes only to the development store, never to the user's Supabase.
const config = await fetch(`${base}/api/config`).then(r => r.json());
assert.equal(config.storage, "local", "API smoke test requires LOCAL_STORE development mode");
const id = `smoke-${randomUUID()}`;
const body = { eventId: id, deviceId: "test-01", sensorType: "rain", wet: true, observedAt: new Date(Date.now() - 60_000).toISOString() };
const send = (data: unknown, token = env.TEST_DEVICE_TOKEN) => fetch(`${base}/api/readings`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(data) });
assert.equal((await send(body, "wrong-token")).status, 401);
assert.equal((await send({ ...body, wet: "yes" })).status, 400);
assert.equal((await send({ ...body, source: "real" })).status, 201);
const duplicate = await send(body); assert.equal(duplicate.status, 200); assert.equal((await duplicate.json()).duplicate, true);
assert.equal((await send({ ...body, wet: false })).status, 409);
assert.equal((await send({ ...body, deviceId: "room-01" })).status, 401);
const day = thaiDay(body.observedAt);
const list = await fetch(`${base}/api/readings?from=${day}&to=${day}&source=test`).then(r => r.json());
assert.equal(list.readings.filter((r: { eventId: string }) => r.eventId === id).length, 1);
assert.equal(list.readings.find((r: { eventId: string }) => r.eventId === id).source, "test");
const real = await fetch(`${base}/api/readings?from=${day}&to=${day}&source=real`).then(r => r.json());
assert.equal(real.readings.some((r: { eventId: string }) => r.eventId === id), false);
assert.equal((await fetch(`${base}/api/readings?from=bad&to=bad`)).status, 400);
assert.equal((await fetch(`${base}/api/weather?lat=999`)).status, 400);
assert.equal((await fetch(`${base}/api/readings?from=2026-02-31&to=2026-03-01`)).status, 400);
const concurrent = await Promise.all(Array.from({ length: 6 }, (_, i) => send({ ...body, eventId: `${id}-concurrent-${i}` })));
assert.ok(concurrent.every(r => r.status === 201));
const after = await fetch(`${base}/api/readings?from=${day}&to=${day}&source=test`).then(r => r.json());
assert.equal(after.readings.filter((r: { eventId: string }) => r.eventId.startsWith(id)).length, 7);
console.log("API smoke passed: authentication, validation, idempotency, conflict, device scope, source separation and date range.");
